nav:
  home: /
  # about: /about/
  articles: /archives/
  # projects: http://github.com/probberechts

# projects_url: http://github.com/probberechts

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/red.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/red.ico
        gravatar: true
      android:
        url: /images/red.png
        gravator: false
      apple:
        url: /images/red.png
        gravator: false
    social_links:
        github: https://github.com/ifelseboyxx
        weibo: https://weibo.com/6463284952/profile?rightmod=1&wvr=6&mod=personinfo
        # Google: 
        # twitter: /
        # facebook: /
        # linkedin: /
    show_all_posts: false
    post_count: 10
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
